### ISSUE TITLE
Load station maps using a wildcard

### ISSUE THREAD

**Issue by hrbonz** [gams/openkongqi#69]
The util function `openkongqi/stations.py:get_station_map()` should be updated to support loading a uuid with a terminating wildcard.

Example:
If I have stations in `us/dc.json` and `us/ca.json` all associated to one source, they will have uuid `us:dc` and `us:ca` respectively. I'm proposing to set the UUID of the source to `us:*` and have `get_station_map()` return an aggregated station map of all station files under `us/`

### TODO
* [x] in `openkongqi/stations.py:get_station_map()`, test if uuid ends with `*`, if it does then create a search uuid by dropping the wildcard from the uuid string, loop through the map keys and merge the dicts from all keys that start with the search uuid.
* [x] add the proper documentation to explain the use of the wildcard
* [x] add test to `test_stations.py` to test loading with or without a wildcard
